lolhelpersite/lolhelpersite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('playerstats/', include('playerstats.urls')),
    path('admin/', admin.site.urls),
]

lolhelpersite/playerstats/urls.py
from django.urls import path

from . import views

app_name = 'playerstats'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<pk>/', views.DetailView.as_view(), name='detail'),
]

lolhelpersite/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

lolhelpersite/playerstats/models.py
from django.db import models

class Player(models.Model):
    puuid = models.CharField(primary_key=True, max_length=78)
    accountid = models.CharField(max_length=56, blank=True, null=True)
    summonerid = models.CharField(max_length=48, blank=True, null=True)
    region = models.TextField(blank=True, null=True)
    tier = models.TextField(blank=True, null=True)
    summonername = models.TextField(blank=True, null=True)
    leaguepoints = models.IntegerField(blank=True, null=True)
    rank = models.TextField(blank=True, null=True)
    wins = models.IntegerField(blank=True, null=True)
    losses = models.IntegerField(blank=True, null=True)
    veteran = models.BooleanField(blank=True, null=True)
    inactive = models.BooleanField(blank=True, null=True)
    freshblood = models.BooleanField(blank=True, null=True)
    hotstreak = models.BooleanField(blank=True, null=True)
    profileiconid = models.IntegerField(blank=True, null=True)
    revisiondate = models.CharField(max_length=13, blank=True, null=True)
    summonerlevel = models.IntegerField(blank=True, null=True)

    class Meta:
       managed = False
       db_table = 'players'

lolhelpersite/polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

lolhelpersite/playerstats/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Player


class IndexView(generic.ListView):
    template_name = 'playerstats/index.html'
    context_object_name = 'highest_rank_player_list'

    def get_queryset(self):
        """
        Return the five highest ranking players

        """

        return Player.objects.filter(
            tier='challenger',
            region='na1'
        ).order_by('-leaguepoints')[:5]


class DetailView(generic.DetailView):
    model = Player
    template_name = 'playerstats/detail.html'
    
    def get_queryset(self):
        return Player.objects

lolhelpersite/polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

lolhelpersite/playerstats/templates/playerstats/detail.html
{% load static %}



<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{{ player.summonername }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'playerstats/style.css' %}">
  </head>

  <body>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <div class="vertical-align-container">
      <div class="content-container">
        <div class="player-info-navbar-container">
          <div class="player-info-navbar">
            <div class="info-container">
              <div class="row-container">
                <div class="previous-rank">
                  <a>Sample Text:</a>
                  <a>S8 Challenger</a>
                  <a>S9 Iron IV</a>
                </div>
              </div>

              <div class="row-container">
                <div class="summoner-icon-container">

                </div>

                <div class="account-summary-info">
                  <div class="ladder-rank-info">
                    Ladder rank 1 (0.0001% of top)
                  </div>
                  <div class="summoner-name-info">
                    <div class="summoner-name">
                      {{ player.summonername }}
                    </div>
                    <div class="region">
                      {{ player.region }}
                    </div>
                  </div>
                  <div class="buttons-container">
                    <div class="update-button">
                      update
                    </div>
                    <div class="favourite-button">
                      favourite
                    </div>
                  </div>
                  <div class="last-updated">
                    Last updated: 1 second ago
                  </div>
                </div>
              </div>
            </div>
            <div class="menu">
              <div class="overview">
                overview
              </div>
              <div class="live-game">
                live game
              </div>
            </div>
          </div>
        </div>

        <div class="match-summary-info-container">

          <div class="ranked-container">
            <div class="solo-ranked-info-container">
              <div class="crest-container">
                <div class="rank-solo-crest">

                </div>
              </div>
              
              <div class="text-container">
                <div class="game-mode">
                  Ranked solo
                </div>
                <div class="player-tier-container">
                  <div class="player-tier">
                    {{ player.tier }}
                  </div>
                  <div class="player-lp">
                    {{ player.leaguepoints }}{{ " LP" }}
                  </div>
                </div>
                <div class="player-winrate-container">
                  <div class="player-winrate">
                    {{ "Winrate 69.0% " }}
                  </div>
                  <div class="player-win-loss-ratio">
                    {{ "(" }}{{ player.wins }}{{ "W " }}{{ player.losses }}{{ "L)" }}
                  </div>
                </div>
              </div>
            </div>

            <div class="flex-ranked-info-container">
              <div class="crest-container">
                <div class="rank-flex-crest">

                </div>
              </div>
              
              <div class="text-container">
                <div class="game-mode">
                  Ranked solo
                </div>
                <div class="player-tier-container">
                  <div class="player-tier">
                    {{ player.tier }}
                  </div>
                  <div class="player-lp">
                    {{ player.leaguepoints }}{{ " LP" }}
                  </div>
                </div>
                <div class="player-winrate-container">
                  <div class="player-winrate">
                    {{ "Winrate 69.0% " }}
                  </div>
                  <div class="player-win-loss-ratio">
                    {{ "(" }}{{ player.wins }}{{ "W " }}{{ player.losses }}{{ "L)" }}
                  </div>
                </div>
              </div>
            </div>
          </div>
          
          <div class="tier-graph-wrapper">
            <div class="tier-graph-container">
              <div class="tier-graph-header">
                Tier Graph
              </div>
              <div class="tier-graph-diagram">
                a diagram of tier vs time goes here
              </div>
            </div>
          </div>

          <div class="other-game-mode-wrapper">
            <div class="other-game-mode-container">
              <div class="game-mode-container">
                <div class="game-mode-title">
                  ARAM
                </div>
                <div class="game-mode-stats">
                  <div class="winrate">
                    <div class="text">Winrate </div>
                    <div class="win-percentage">
                      {{ "69.0% " }}
                    </div>
                  </div>
                  <div class="player-win-loss-ratio">
                    {{ "420W 69L" }}
                  </div>
                </div>
              </div>

              <div class="game-mode-container">
                <div class="game-mode-title">
                  URF
                </div>
                <div class="game-mode-stats">
                  <div class="winrate">
                    <div class="text">Winrate </div>
                    <div class="win-percentage">
                      {{ "69.0% " }}
                    </div>
                  </div>
                  <div class="player-win-loss-ratio">
                    {{ "420W 69L" }}
                  </div>
                </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="stats-by-champion-container">
          <div class="champions-navbar">
            <div class="champions-navbar-option">Summoner's Rift</div>
            <div class="champions-navbar-option">ARAM</div>
            <div class="champions-navbar-option">URF</div>
            <div class="champions-navbar-option">event mode</div>
          </div>

          <div class="detail-navbar">
            <div class="option-container">
              <div class="option"><div class="option-text">Solo Ranked</div></div>
              <div class="option"><div class="option-text">Flex Ranked</div></div>
              <div class="option"><div class="option-text">Normal</div></div>
            </div>
            <div class="option-container">
              <div class="option"><div class="option-text">All</div></div>
              <div class="option"><div class="option-text">Top</div></div>
              <div class="option"><div class="option-text">Jungle</div></div>
              <div class="option"><div class="option-text">Mid</div></div>
              <div class="option"><div class="option-text">Bot</div></div>
              <div class="option"><div class="option-text">Support</div></div>

            </div>
          </div>

          <div class="champion-stats">
            <div class="table-title">
              Champion Stats
            </div>
            <div class="table-content">
              <div class="table-header">
                <div class="header-element champion">Champion</div>
                <div class="header-element">Winrate</div>
                <div class="header-element">Games</div>
                <div class="header-element">Wins</div>
                <div class="header-element">Losses</div>
                <div class="header-element">KDA</div>
                <div class="header-element">Kills</div>
                <div class="header-element">Deaths</div>
                <div class="header-element">Assists</div>
                <div class="header-element">Double Kills</div>
                <div class="header-element">Triple Kills</div>
                <div class="header-element">Quadra Kills</div>
                <div class="header-element">Penta Kills</div>
                <div class="header-element">CS</div>
                <div class="header-element">CS/min</div>
              </div>

              <div class="table-row">
                <div class="row-element champion">Ahri</div>
                <div class="row-element">100%</div>
                <div class="row-element">420</div>
                <div class="row-element">69</div>
                <div class="row-element">0</div>
                <div class="row-element">420</div>
                <div class="row-element">420</div>
                <div class="row-element">1</div>
                <div class="row-element">0</div>
                <div class="row-element">69</div>
                <div class="row-element">69</div>
                <div class="row-element">69</div>
                <div class="row-element">69</div>
                <div class="row-element">420</div>
                <div class="row-element">69</div>
              </div>
            </div>
          </div>
        </div>

        <div class="match-history-container">
          <a>match-history-container</a>
        </div>

        <div class="recently-played-with-container">
          <a>recently-played-with-container</a>
        </div>
      </div>

    </div>



  </body>
</html>
<!-- 
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'playerstats/style.css' %}">

<h1>{{ player.summonername }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h2>{{ "Region: " }}{{ player.region }}</h2>
<h2>{{ "Rank: " }}{{ player.tier }}</h2>
<h2>{{ "LP: " }}{{ player.leaguepoints }}</h2>
<h2>{{ "Wins: " }}{{ player.wins }}</h2>
<h2>{{ "Losses: " }}{{ player.losses }}</h2> -->

lolhelpersite/playerstats/templates/playerstats/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'playerstats/style.css' %}">

<h1>{{ "Top 5 Players in NA1" }}</h1>

{% if highest_rank_player_list %}
    <ol>
    {% for player in highest_rank_player_list %}
    <li><a href="{% url 'playerstats:detail' player.puuid %}">{{ player.summonername }}</a>{{ player.leaguepoints }}</li>
    {% endfor %}
    </ol>
{% else %}
    <p>No data available.</p>
{% endif %}

lolhelpersite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

lolhelpersite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

lolhelpersite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>